# Generated by Django 5.2 on 2025-05-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="person",
            name="contactNumber",
            field=models.CharField(
                default=None, max_length=20, verbose_name="Contact Number"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
