# Generated by Django 5.2 on 2025-05-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_person_address_alter_person_contactnumber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="address",
        ),
    ]
