# Generated by Django 5.2 on 2025-05-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_remove_person_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="person",
            name="blood_group",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
