# Generated by Django 5.2 on 2025-05-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_person_address_person_blood_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="address",
        ),
    ]
