# Generated by Django 5.2 on 2025-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_remove_person_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.TextField(default=""),
        ),
    ]
