# Generated by Django 5.2 on 2025-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_person_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
