# Generated by Django 5.2 on 2025-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_alter_person_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(null=True, blank=True, default=''),
        ),
    ]
