# Generated by Django 5.2 on 2025-05-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_auto_20250502_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.TextField(default=""),
        ),
    ]
