# Generated by Django 5.0 on 2025-05-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_person_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
